### ISSUE TITLE
Some recently added fonts missing

### ISSUE THREAD

**Issue by Finii** [sumo300/chocolatey-nerd-fonts#16]
Dear @sumo300 

I came here to check if we can remove the chocolatey subdirectories from the Nerd Fonts repo:
https://github.com/ryanoasis/nerd-fonts/tree/master/chocolatey

It looks outdated and unmaintained and obviously you do not need it (I guess).
I will remove it then.

But when I saw your excellent project here, I noticed that some fonts seem to be missing, for example
* Martian
* Monaspace/Monaspice
* Zed

I can not see how your automation works here, but maybe I can help.

**Comment by sumo300** [comment]
@Finii Missing fonts is an issue due to the way the automation works and that I haven't figured out a way to make that part dynamic.  Those fonts would need to be added manually with their automation scripts and the build run again which would deploy the packages to chocolatey.

Feel free to try and add them and submit a pull request but I'll try to remember to get to it soon and get those fonts added.

**Comment by sumo300** [comment]
Missing fonts have been published and are pending review on chocolatey.org.
